exercises_processor:
  keys:
    exercise_names_key: 'Exercise Name'
    equipments_key: 'Equipment Used'
    skill_levels_key: 'Skill Level'
    muscles_key: 'Muscle Groups Targeted (%)'
    exercise_groups_key: 'Exercise Group'
    body_parts_key: 'Body Part'

exercises_planner:
  skills:
    beginner: 0
    intermediate: 1
    advanced: 2

exercises_formatter:
  print_exercises_names: true
  print_exercises_group: true
  print_body_part: true
  print_muscle_groups_targeted: true



